import { Rule } from "../../types";

export const defaultKeyWords: Rule[] = [
  {
    keywords: [
      "Mcdonald",
      "Panda Express",
      "Hot Chicken",
      "Chick-Fil-A",
      "Mexican food",
      "Pizza",
      "Restaurant",
      "BBQ",
      "Grill",
      "Five Guys",
      "Chipotle",
      "Dining",
      "In-N-Out",
      "Diner",
      "Sushi",
      "Taco",
      "Burger",
      "Shake Shack",
      "Wendy",
      "Subway",
      "Domino",
      "Papa John",
      "Panera",
      "Olive Garden",
      "Applebee",
      "Buffalo Wild",
      "Chili",
      "Noodle",
      "Ramen",
      "Boba",
      "Wingstop",
      "Raising Cane",
      "Popeye",
      "KFC",
      "Taco Bell",
      "Del Taco",
      "Jack in the Box",
      "Carl",
      "Hardee",
      "Denny",
      "IHOP",
      "Waffle House",
    ],
    category: "Restaurants",
  },
  {
    keywords: [
      "Walmart",
      "Target",
      "Costco",
      "Grocery",
      "Whole Foods",
      "Trader Joe",
      "Safeway",
      "Kroger",
      "Publix",
      "Aldi",
      "Sprouts",
      "Ralph",
      "Vons",
      "Food",
      "Market",
      "Fresh",
      "HEB",
      "Wegmans",
      "Stop & Shop",
      "Giant",
      "Meijer",
      "Winn-Dixie",
      "Erewhon",
    ],
    category: "Groceries",
  },
  {
    keywords: [
      "Donut",
      "Snack",
      "Chip",
      "Candy",
      "Cookie",
      "Bakery",
      "Pretzel",
      "Popcorn",
      "7-Eleven",
      "Circle K",
      "Convenience",
      "Wawa",
      "QuikTrip",
      "Sheetz",
    ],
    category: "Snacks",
  },
  {
    keywords: [
      "Uber",
      "Lyft",
      "MTA",
      "Rail",
      "Flix",
      "Parking",
      "Toll",
      "Transit",
      "Metro",
      "Bus",
      "Train",
      "Amtrak",
      "BART",
      "Caltrain",
      "Greyhound",
      "Airport",
      "Shuttle",
      "Zipcar",
      "Lime",
      "Bird",
      "Scooter",
      "E-Bike",
    ],
    category: "Transportation",
  },
  { keywords: ["Gas", "Shell", "Chevron", "Exxon", "BP", "Mobil", "Arco", "Valero", "Sunoco"], category: "Gas" },
  {
    keywords: [
      "Coffee",
      "Campus Market",
      "Starbucks",
      "Espresso",
      "UU MARKET",
      "Cafe",
      "Dutch Bros",
      "Peet",
      "Blue Bottle",
      "Dunkin",
      "Tim Horton",
    ],
    category: "Energy Drink",
  },
  {
    keywords: [
      "Payroll",
      "Salary",
      "CalMatters",
      "Mobile Deposit",
      "Interest Payment",
      "Deposit",
      "Direct Deposit",
      "Venmo",
      "Zelle",
      "CashApp",
      "Refund",
    ],
    category: "Income",
  },
  {
    keywords: [
      "Monthly Service Fee",
      "Spotify",
      "APPLE.COM/BILL",
      "Netflix",
      "Hulu",
      "Disney",
      "HBO",
      "Paramount",
      "YouTube Premium",
      "Amazon Prime",
      "Peacock",
      "Crunchyroll",
      "Twitch",
      "Adobe",
      "Microsoft",
      "Google One",
      "iCloud",
      "Dropbox",
      "LastPass",
      "NordVPN",
      "ExpressVPN",
      "Duolingo",
      "Headspace",
      "Calm",
    ],
    category: "Subscriptions",
  },
  {
    keywords: ["Audible", "Books", "Barnes & Noble", "Book", "Kindle", "Library"],
    category: "Books",
  },
  {
    keywords: ["Pub", "Brew", "Brewing", "Bar", "Tavern", "Lounge", "Nightclub"],
    category: "Bars",
  },
  { keywords: ["Golf", "Topgolf"], category: "Golf" },
  {
    keywords: ["BEVERAGES & MOR", "Liquor", "Wine", "Spirits", "Total Wine", "BevMo"],
    category: "Alcohol",
  },
  { keywords: ["Field", "Stadium", "Arena", "Ballpark", "Ticketmaster", "SeatGeek", "StubHub"], category: "Sports Games" },
  { keywords: ["Fines", "Fine", "Parking Ticket", "DMV", "Citation"], category: "Traffic Tickets" },
  {
    keywords: [
      "Gym",
      "Planet Fitness",
      "LA Fitness",
      "24 Hour Fitness",
      "Equinox",
      "Anytime Fitness",
      "CrossFit",
      "SoulCycle",
      "Peloton",
      "YMCA",
      "Orange Theory",
      "F45",
    ],
    category: "Gym",
  },
  {
    keywords: [
      "Amazon",
      "eBay",
      "Etsy",
      "Wayfair",
      "Best Buy",
      "Newegg",
      "B&H",
      "Chewy",
      "Shopify",
      "AliExpress",
      "SHEIN",
      "Temu",
    ],
    category: "Online Shopping",
  },
  {
    keywords: [
      "Clothes",
      "H&M",
      "Zara",
      "Gap",
      "Old Navy",
      "Nike",
      "Adidas",
      "Lululemon",
      "TJ Maxx",
      "Nordstrom",
      "Macy",
      "Bloomingdale",
      "Forever 21",
      "Uniqlo",
      "Patagonia",
      "North Face",
    ],
    category: "Clothes",
  },
  {
    keywords: [
      "Electric",
      "PG&E",
      "Con Edison",
      "Water",
      "Sewer",
      "Comcast",
      "Xfinity",
      "AT&T",
      "Verizon",
      "T-Mobile",
      "Internet",
      "Phone Bill",
      "Utility",
      "Gas Bill",
      "National Grid",
      "Duke Energy",
    ],
    category: "Utilities",
  },
  {
    keywords: [
      "CVS",
      "Walgreens",
      "Rite Aid",
      "Pharmacy",
      "Doctor",
      "Hospital",
      "Clinic",
      "Dental",
      "Optometrist",
      "Medical",
      "Health",
      "Urgent Care",
      "Lab",
      "Prescription",
    ],
    category: "Healthcare",
  },
  {
    keywords: [
      "Rent",
      "Mortgage",
      "HOA",
      "Lease",
      "Landlord",
    ],
    category: "Housing",
  },
  {
    keywords: [
      "Venmo",
      "Zelle",
      "CashApp",
      "PayPal",
      "Wire Transfer",
      "ATM",
    ],
    category: "Transfer",
  },
  {
    keywords: [
      "Tuition",
      "University",
      "College",
      "Campus",
      "Textbook",
      "Student",
      "School",
    ],
    category: "College",
  },
  {
    keywords: [
      "Hotel",
      "Airbnb",
      "Vrbo",
      "Flight",
      "Southwest",
      "Delta",
      "United",
      "American Airlines",
      "Spirit",
      "Frontier",
      "Expedia",
      "Booking.com",
      "Kayak",
    ],
    category: "Trips",
  },
];
